#!/usr/bin/env python3
"""Generates the shared StairsBody suite from test/test_stairs.gd.

StairsCharacter and StairsBody share no base class below CollisionObject3D, so one
hand-written suite could only drive both through untyped calls. Instead the
StairsCharacter suite stays the single source, and this writes a typed copy aimed
at StairsBody, minus the cases that exercise something StairsBody does not have.
The output is gitignored; test/run.sh regenerates it on every run.

StairsBody's own machinery is tested in test/test_stairs_body.gd, by hand.

    python3 test/gen_stairs_body_suite.py
"""

import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
SOURCE = ROOT / "test" / "test_stairs.gd"
OUT_DIR = ROOT / "test" / "generated"
OUT_SCRIPT = OUT_DIR / "test_stairs_body_shared.gd"
OUT_SCENE = OUT_DIR / "test_stairs_body_shared.tscn"

# Case number (or helper name) -> why StairsBody skips it. A case missing here
# runs against StairsBody, so a new case in test_stairs.gd is shared by default.
DROPPED = {
    "07": "drives stair_step_up/stair_step_down, StairsCharacter's step API",
    "08": "subclasses StairsCharacter",
    "10": "margin resolution from the collider export; StairsBody has safe_margin",
    "11": "the legacy 'Collider' child fallback",
    "12": "subclasses StairsCharacter",
    "15": "the legacy _step_height property shim",
    "22": "drives stair_step_up",
    "23": "the legacy _step_height property shim",
    "24": "the grounded flag, which StairsBody does not have",
    "36": "subclasses StairsCharacter; test_stairs_body.gd has its own",
    "38": "drives stair_step_up and reads grounded",
    "44": "StairsBody climbs from the main slide, so one forward-leg iteration is "
    "not the old single sweep",
    "45": "controls for StairsCharacter's leftover forward leg, which StairsBody "
    "does not have; test_stairs_body.gd b04 is its control",
    "46": "split_move, which StairsBody does not have",
    "47": "split_move, which StairsBody does not have",
    "_resolved_margin": "helper for case 10 only",
}

# Text the rewrite depends on, each expected exactly once. If test_stairs.gd moves
# away from one, the generator stops rather than emit a suite that quietly still
# assigns the collider export or preloads the subclass.
REMOVALS = [
    "\n\tif not legacy_node_name:\n\t\tc.collider = shape_node",
    'const SUBCLASS_SCRIPT: Script = preload("res://test/subclass_character.gd")\n',
]

SCENE = """[gd_scene format=3]

[ext_resource type="Script" path="res://test/generated/test_stairs_body_shared.gd" id="1"]

[node name="TestStairsBodyShared" type="Node3D"]
script = ExtResource("1")
"""


def _dropped(name: str) -> bool:
    if name in DROPPED:
        return True
    match = re.match(r"_case_(\d+)_", name)
    return match is not None and match.group(1) in DROPPED


def _removed_lines(lines: list[str]) -> set[int]:
    starts = [i for i, line in enumerate(lines) if line.startswith("func ")]
    removed: set[int] = set()
    found: set[str] = set()
    for n, start in enumerate(starts):
        name = re.match(r"func (\w+)", lines[start]).group(1)
        if not _dropped(name):
            continue
        found.add(name)
        end = starts[n + 1] if n + 1 < len(starts) else len(lines)
        # The next function's doc comment and the blank lines before it stay.
        while end > start and (lines[end - 1].startswith("##") or not lines[end - 1].strip()):
            end -= 1
        begin = start
        while begin > 0 and lines[begin - 1].startswith("##"):
            begin -= 1
        removed.update(range(begin, end))
        call = re.compile(r"^\tawait %s\(\)$" % re.escape(name))
        removed.update(i for i, line in enumerate(lines) if call.match(line))
    missing = [
        key
        for key in DROPPED
        if not any(key == f or f.startswith("_case_%s_" % key) for f in found)
    ]
    if missing:
        sys.exit("gen_stairs_body_suite: no function for dropped %s" % ", ".join(missing))
    return removed


def main() -> None:
    lines = SOURCE.read_text().split("\n")
    removed = _removed_lines(lines)
    text = "\n".join(line for i, line in enumerate(lines) if i not in removed)
    for snippet in REMOVALS:
        if text.count(snippet) != 1:
            sys.exit("gen_stairs_body_suite: expected exactly one of %r" % snippet)
        text = text.replace(snippet, "")
    text = text.replace("StairsCharacter", "StairsBody")
    header = "# GENERATED by test/gen_stairs_body_suite.py from test/test_stairs.gd. Do not edit.\n"
    OUT_DIR.mkdir(exist_ok=True)
    OUT_SCRIPT.write_text(header + text)
    OUT_SCENE.write_text(SCENE)


if __name__ == "__main__":
    main()
